### ISSUE TITLE
 CreateProcessWithTokenW

### ISSUE THREAD

**Issue by 23jdn** [Aquilao/GoTokenTheft#1]
CreateProcessWithTokenW() error: A required privilege is not held by the client

**Comment by Aquilao** [comment]
shell 的权限不够，是管理员权限的 shell 吗？

**Comment by 23jdn** [comment]
是的,就这一步没成功   -

**Comment by Aquilao** [comment]
有管理员权限的话就不该有问题了，测试环境里有什么杀软吗，关掉杀软试试？

**Comment by 23jdn** [comment]
无杀软环境

**Comment by 23jdn** [comment]
c:\Users\Anonymous\Desktop>whoami /priv

特权信息
----------------------

特权名                                    描述                               状态
========================================= ================================== ======
SeIncreaseQuotaPrivilege                  为进程调整内存配额                 已禁用
SeSecurityPrivilege                       管理审核和安全日志                 已禁用
SeTakeOwnershipPrivilege                  取得文件或其他对象的所有权         已禁用
SeLoadDriverPrivilege                     加载和卸载设备驱动程序             已禁用
SeSystemProfilePrivilege                  配置文件系统性能                   已禁用
SeSystemtimePrivilege                     更改系统时间                       已禁用
SeProfileSingleProcessPrivilege           配置文件单一进程                   已禁用
SeIncreaseBasePriorityPrivilege           提高计划优先级                     已禁用
SeCreatePagefilePrivilege                 创建一个页面文件                   已禁用
SeBackupPrivilege                         备份文件和目录                     已禁用
SeRestorePrivilege                        还原文件和目录                     已禁用
SeShutdownPrivilege                       关闭系统                           已禁用
SeDebugPrivilege                          调试程序                           已禁用
SeSystemEnvironmentPrivilege              修改固件环境值                     已禁用
SeChangeNotifyPrivilege                   绕过遍历检查                       已启用
SeRemoteShutdownPrivilege                 从远程系统强制关机                 已禁用
SeUndockPrivilege                         从扩展坞上取下计算机               已禁用
SeManageVolumePrivilege                   执行卷维护任务                     已禁用
SeImpersonatePrivilege                    身份验证后模拟客户端               已启用
SeCreateGlobalPrivilege                   创建全局对象                       已启用
SeIncreaseWorkingSetPrivilege             增加进程工作集                     已禁用
SeTimeZonePrivilege                       更改时区                           已禁用
SeCreateSymbolicLinkPrivilege             创建符号链接                       已禁用
SeDelegateSessionUserImpersonatePrivilege 获取同一会话中另一个用户的模拟令牌 已禁用

C:\Users\Anonymous\Desktop>uac.exe -p 8828 -c cmd.exe
2023/01/04 11:22:37 [+] Process Pid:  8828
2023/01/04 11:22:37 [+] Execute Command:  dir
2023/01/04 11:22:37 [+] GetCurrentProcess() success
2023/01/04 11:22:37 [+] OpenProcessToken() success
2023/01/04 11:22:37 [+] LookupPrivilegeValue() success
2023/01/04 11:22:37 [+] AdjustTokenPrivileges() success
2023/01/04 11:22:37 [+] OpenProcess() start.
2023/01/04 11:22:37 [+] OpenProcessToken() success
2023/01/04 11:22:37 [+] DuplicateTokenEx() success
2023/01/04 11:22:37 [-] CreateProcessWithTokenW() error: A required privilege is not held by the client.

**Comment by Aquilao** [comment]
暂时没办法复现这个问题。我的环境权限和你相同，但可以正常运行。

![image](https://user-images.githubusercontent.com/25531497/210703812-2b781620-5f66-4a07-af30-ab8c552a18fd.png)

猜测可能是目标进程的问题，你窃取的目标进程是哪个？可以换几个进程试试，比如我试了 lsass 是可以的，而且Defender 不拦~

**Comment by 23jdn** [comment]
好的，我多测测
